"""The rules video, beat by beat: (frame id, section, timecode, voiceover, what moves).
Source of truth for the voiceover wording; imported by storyboard.py and render/build.py."""
# (frame, section, time, voiceover, what moves)
BEATS = [
 ('0-tap', '1 · Cold open', '0:00', '', 'A card reader on a white screen. A big Clipper Conquest card swipes in, taps (beep, the reader lights green), then swipes out, wiping the screen white behind it.'),
 ('1b-title', '1 · Cold open', '0:08', 'Two teams. Forty-one neighborhoods. One clock. This is Clipper Conquest.', 'A few neighborhoods fill red and blue; the title slides in.'),
 ('2a-grey', '2 · The basic idea', '0:14', 'Clipper Conquest is played by two teams, the red team and the blue team, that race to conquer as many San Francisco neighborhoods as possible. Whichever team has more neighborhoods when the clock hits zero is the winner.', 'Map resets to grey; the 41 counts up as neighborhoods ripple.'),
 ('2b-challenges', '2 · The basic idea', '0:26', "Every one of the city's 41 neighborhoods has three unique challenges. For example, one challenge might ask you to get three antique arcade machines running at the same time. Another might ask two teammates to count the sea lions at Pier 39 and agree on the number. Whichever team has completed more of a neighborhood's challenges holds it.", 'Zoom to North Beach, which turns yellow; three challenge cards slide in one by one.'),
 ('3a-muni', '3 · Muni only', '0:42', 'You get around on Muni, and only Muni: buses, Metro, streetcars and cable cars. No BART, no Caltrain, no cars and no bikes. And no running unless a challenge says to. You can only speedwalk.', 'Pull back; Muni lines draw in their real colors. The red team dot rides the F-line and the Powell-Mason cable car to North Beach. Checklist ticks in.'),
 ('4a-phone', '4 · Photo proof', '0:55', 'When you finish a challenge, take a photo. Every completion needs one.', 'Phone slides up on Get to Coit Tower; camera shutter click.'),
 ('4b-upload', '4 · Photo proof', '1:00', 'Then upload it in the app and tap Complete. The moment you log it is the moment it counts.', 'A Coit Tower photo drops in; thumb taps Complete; it becomes a check with the time, 11:58.'),
 ('5a-empty', '5 · Conquering', '1:05', "Here's how that plays out in North Beach.", 'Back on North Beach, empty timeline.'),
 ('5b-blue', '5 · Conquering', '1:09', "The blue team completes one. North Beach is the blue team's.", 'Row slides into the timeline; North Beach floods blue; badge 0-1.'),
 ('5c-tied1', '5 · Conquering', '1:13', "But be careful. The other team can steal a neighborhood by completing more of its challenges than you. The red team completes one. Now it's one each, but the blue team got there first, so North Beach stays blue.", 'Red row; badge ticks to 1-1; North Beach stays blue (the blue team got there first).'),
 ('5d-flip', '5 · Conquering', '1:21', 'And then another. Two beats one. The red team steals North Beach.', 'Third row; North Beach flips red; highlight row "The red team steals North Beach".'),
 ('5e-tie2', '5 · Conquering', '1:26', "The blue team answers with a second. Now it's two each. So who holds it?", 'Fourth row; North Beach fills with red and blue stripes and freezes.'),
 ('6a-tiebreak', '6 · Ties and locks', '1:31', 'Ties go to whichever team reached that count first. The red team logged its second at 11:58. The blue team logged its second at 12:30. So the red team keeps North Beach.', 'Timeline slides in; a marker sweeps left to right; flag pops at 11:58.'),
 ('6b-sweep', '6 · Ties and locks', '1:42', 'Complete all three and the neighborhood is locked. No one can steal it.', 'Cut to Hayes Valley: three checks, spaced out to feel slow; then the lock snaps shut with a clunk.'),
 ('7a-costs', '7 · Quick or locked', '1:51', "So there's a choice. One challenge grabs a neighborhood fast, but it can be stolen. All three lock it, but that takes time. Here, the red team zips around grabbing neighborhoods, while the blue team locks down a few.", "Fresh map; the red dot zips around claiming neighborhoods with one challenge each, while the blue dot slowly locks a few."),
 ('8a-end', '8 · Close', '2:02', 'Whichever team has more neighborhoods when the clock hits zero wins. Every rule and every challenge is in the guide.', 'Map fades; end card with the guide QR code.'),
]
